### ISSUE TITLE
Can't install create-secrets

### ISSUE THREAD

**Issue by msilvestre** [magda-io/magda-config#13]
Hi,

I was following the tutorial to run this locally on OSX Darwin 19.6.0, but I can't install create-secrets.
It is step 6 of the following: https://github.com/magda-io/magda-config/blob/master/existing-k8s.md

It gives me error below:

Thanks.

```
 npm install --global @magda/create-secrets                       
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/miguel.silvestre/.nvm/versions/node/v14.15.0/lib/node_modules/@magda/create-secrets/bin/create-secrets.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/miguel.silvestre/.nvm/versions/node/v14.15.0/lib/node_modules/@magda/create-secrets/bin/create-secrets.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miguel.silvestre/.npm/_logs/2020-11-11T12_23_53_421Z-debug.log
```

**Comment by t83714** [comment]
@msilvestre 
Can you try node 12 or 10 to see if it works?

**Comment by IKrajciova** [comment]
Hello, did you resolve the issue? I have got exactly the same issue. 
npm --version
v6.14.15

node --version
v12.22.7

Please help with this???

**Comment by t83714** [comment]
@IKrajciova  if you use node 12 or node 10, it should work.
Could you please share any error messages you might have for your issue?
By the way, since Magda v1.0.0, Magda's helm chart can auto-generate / manage essential secrets that are required by a standard installation.
Thus, unless you want to turn on any "plugins", you don't have to use "create-secret" to create the essential secrets before the Magda installation.

**Comment by IKrajciova** [comment]
Thank you for your fast response. 

The error I am receiving is:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /usr/lib/node_modules/@magda/create-secrets/bin/create-secrets.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/@magda/create-secrets/bin/create-secrets.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-24T07_44_18_640Z-debug.log
```

**Comment by t83714** [comment]
@IKrajciova I can confirm that it's a bug we introduced into our CI pipelines recently which only impact recent prerelease v1.1.0-alpha.2 (when I checked the CI pipeline log).

I've fixed this issue: https://github.com/magda-io/magda/issues/3270

And release a new version v1.1.0-alpha.3.

If you try to delete the current version and reinstall it, it should work.

Thanks again for reporting this issue.

**Comment by IKrajciova** [comment]
Thank you very much for your fast response.

It resolved this issue.
