### ISSUE TITLE
How to set password for the admin user

### ISSUE THREAD

**Issue by monomoti** [magda-io/magda-config#14]
I successfully deployed magda using terraform.
But I coudn't find a setting for admin password, and  I can't access /auth/admin or /admin.
Is there a way to change password for admin user?

**Comment by t83714** [comment]
@monomoti We also have a spectrum chat room: https://spectrum.chat/magda 
probably easier to discuss usage issue there.
The default installation only enabled SSO to data.gov.au CKAN.
If you already login to the system, there will be a Magda user created during the SSO process.
We don't have a tool to change a standard user to an admin user (**We will create one dedicate tool for this in near future**).
You can do it manually by following:
- Instruction section 16: https://github.com/magda-io/magda-config#16-what-now
- And [FAQ: how-do-i-make-myself-an-admin](https://github.com/magda-io/magda-config#how-do-i-make-myself-an-admin)
The current Admin area doesn't provide too much functions besides functions allows you to customise colour themes & home page. Most admin job actually need to complete via update Helm chart config value.

You probably want to play around by follow the instructions of [section 16](https://github.com/magda-io/magda-config#16-what-now) first.

**Comment by monomoti** [comment]
@t83714 I got it. I created a data.gov.au CKAN account and signed in my magda instance then changed "isAdmin" to TRUE in the data base.

Thank you for the quick reply.
